### ISSUE TITLE
[jorg] Contact form show only up, if you choose the right group.

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#100] opened 2017-06-20 08:43 UTC
We have to many support requests here: https://www.joomla.org/media-contact.html
@tonypartridge idea was:

> I was planning on making it a selection contact form
> Why are you contacting us today? For Media Support? For Technical Support Etc
> and only on to contact marketing team it shows the contact form
> else prompts them to go to X Y Z

**Comment by tonypartridge** [comment] 2017-06-20 08:57
Test

**Comment by tonypartridge** [comment] 2017-06-21 09:23
Please see:
http://repository.joomla.org/media-contact.html

**Comment by parthlawate** [comment] 2017-06-21 09:34
Can you update the part of tech support and any ones that point to the Forums to say --

For technical support, please visit the Joomla Community Forums here: https://forum.joomla.org or the Joomla Stack Exchange https://joomla.stackexchange.com/

**Comment by Sandra97** [comment] 2017-06-21 09:36
And please add the bang to Joomla, for the moment it's still compulsory

**Comment by tonypartridge** [comment] 2017-06-21 10:08
thanks @parthlawate and @Sandra97 now updated. I wasn't sure about the bang so tried to leave it out. I always get it confused when it should or shouldn't be included lol.

**Comment by Sandra97** [comment] 2017-06-21 10:09
Don't worry, everybody is confused with it. And if nobody understands a rule, it's just mean the rule is bad ;)

**Comment by tonypartridge** [comment] 2017-06-21 10:24
So true!

**Comment by ufuk-avcu** [comment] 2017-06-21 11:18
I go through 500 Mails now and the 95% of are because of they have no access to Joomla backend - lost password, forgot password, whatever... Maybe we can have this option also and send them to the right docs.

**Comment by tonypartridge** [comment] 2017-06-21 12:14
Yep sounds good will add it in

**Comment by zero-24** [comment] 2017-06-21 12:58
What about pointing to issues.joomla.org for "i have found a bug" over the github page?

**Comment by franz-wohlkoenig** [comment] 2017-06-21 13:06
would send first users to Forums as main Page for Requests. Cause its often not clear if its a Bug or expected Behaviour. From Forum as first clearing Page would  made an issue on Issue-Tracker/Github.

**Comment by tonypartridge** [comment] 2017-06-21 13:08
Great point will be @zero-24 now updated. @ufuk-avcu I've also added your question and pointed them to TechnicalSupportForums answer. 

What about explaining the forums then advising if they are 100% sure it is a bug you can use X as we don't want to detract offical bug reports?

**Comment by franz-wohlkoenig** [comment] 2017-06-21 13:15
it looks like People wrote on marketing or Github cause they don't find the "right" Page. Its not fault of People its about Joomla to make this more clear so people don't have to read "please wrote on forum".

**Comment by tonypartridge** [comment] 2017-06-24 22:00
Where are we with this? Can we get to some agreement to push it live or scrap it?

**Comment by Sandra97** [comment] 2017-06-24 22:20
@tonypartridge,  few things:

- nothing is displayed when I click on "I need technical support"
- I can't access to the backend': I think it's better to link to the forum and JDocs
- I have found a buf: nothing is displayed. Please link it to issues.joomla.org
- Nothing is dispalyed for my website is down': link it to the forum

Personally, I would do it a bit differently:
- I need support for my website => forum + JDocs
- I have trouble with my administrator login = JDocs tutorial
- I'm looking for Joomla experts => resources
- I'm looking for tutorials => JDocs + Training
- I have issue with an extension = JED or contact the developer
- I found a bug in Joomla Core => Issue Tracker
- And media of course!

I don't have any issue with merging it from the repo to jorg. 
@parthlawate and @ufuk-avcu, feedback please.

**Comment by parthlawate** [comment] 2017-06-25 03:52
Let's go ahead with it ! And yeah like Sandra's idea to link to the correct JDoc tutorials or just Jdocs where needed

**Comment by tonypartridge** [comment] 2017-06-27 10:33
@Sandra97 changes made as requested. Please see:
http://repository.joomla.org/media-contact.html

**Comment by ufuk-avcu** [comment] 2017-06-27 10:36
I tested all the links and they work fine. @tonypartridge great job! Thank you!

**Comment by Sandra97** [comment] 2017-06-27 10:39
Fine for me. Thanks Tony! Now my turn to work

**Comment by Sandra97** [comment] 2017-06-27 15:49
Thank you a lot @tonypartridge!! You made my life easier :)
The form is merged to jorg and works fine. 
Closing this issue. 
Re-open if needed.

**Closed by Sandra97** 2017-06-27 15:49 UTC
