### ISSUE TITLE
Events and news module in back end

### ISSUE THREAD

**Issue by netamity** [joomla/joomla-marketing#112] opened 2017-07-29 10:12 UTC
I've just installed Wordpress for the first time to see how the other side live, and I noticed that they have a News & Events module in the administration panel that is showing events near me. I thought that was clever, and a great way to get important info out to users, and encourage local events.
Has this type of thing ever been considered for Joomla? I think it'd be a great marketing, news dissemination and community-building tool. Obviously it could be easily collapsible/unpublishable if it wasn't of interest but maybe displayed by default as part of the Joomla core.
What do others think?

**Comment by Sandra97** [comment] 2017-07-29 10:23
Joomla! latest news are already displayed in the backend. 
The backend is not a promotional/marketing place, it's a working place. 
Don't turn the backend into a marketing tool.
It's not because Wordpress does something that Joomla has to do it. We don't have the same target.

**Comment by Joomv** [comment] 2017-07-29 10:27
We've discussed this.  It is a good idea, but we don't have the scope of WP as far as reach though.  Nothing to stop us promoting JAB and JWC in the news section, but given the number of JUG's and JDay's we have doing what WP does would possibly do more harm than good given how spread out they are.

**Comment by netamity** [comment] 2017-07-29 10:30
Ok, great, that's a strong no. I just thought it was worth suggesting, and I see your point about keeping things focussed on work. I certainly wasn't suggesting that because Wordpress was doing something that Joomla should follow, but neither should we automatically exclude a good idea because Wordpress are using it in order to assert our difference (I understand you don't see this as a 'good' idea)
I'd use it if it were there (I'm sorry, I can't find it).

**Comment by Sandra97** [comment] 2017-07-29 10:32
It was worth suggesting, all suggestions are welcome as it allows to discuss, share different views and then to move forward.

**Comment by netamity** [comment] 2017-07-29 10:35
Where is the latest news in the back end Sandra? Is it just an occasional thing?

**Comment by Sandra97** [comment] 2017-07-29 10:39
It's not an occasional thing, news are displayed in the backend since a long time
Navigate to `components` ->`Post-installation Messages` and you'll see the news feed on the right

**Comment by MATsxm** [comment] 2017-07-29 10:47
such a useful com_
knowing I have better to do while I'm in an install process...

**Comment by tonypartridge** [comment] 2017-07-29 11:11
I actually think a Joomla! News &Events component would be warranted which can be disabled. We have custom admin menus so it's just enlightening users who wish to click it.

**Comment by parthlawate** [comment] 2017-07-30 02:24
I have proposed this in the past and met a strong opposition. IMHO the Joomla backend is the only place we have which has the maximum reach compared to any of our other channels. I still don't see a problem in making it an optional that no just like stats is..

**Comment by netamity** [comment] 2017-07-30 12:09
Yes, I wasn't expecting such a strong visceral reaction when I suggested it! No one would be forced to keep it in their panel, you could just un-publish it. It seems to me like we're missing a HUGE opportunity to connect with people and potentially enhance the community for some notion of keeping the administration panel pure. 
I'd consider creating a back end module for news and events using the rss feeds here: https://www.joomla.org/rss-news-feeds.html . It might be worth creating as an extension so that people can add it in if they wanted it, but the real power would be if it were part of the core install. I can't help thinking that far more people would keep it published and engage with the content if it was shipped with Joomla than would proactively install it themselves.
I like the idea of making it a post install option like stats so that the purists can reject it but we give everyone else ample opportunity to buy in to the idea.

**Comment by mbabker** [comment] 2017-07-30 15:20
The problem isn't so much sharing information with users.  The problem to me is turning a user's backend into a marketing platform for our use.  For a vast majority of people who are using Joomla, the most relevant piece of content we can give them is already in their backend, the release news visible in the postinstall component.  Anything beyond that we start making an assumption that the people using Joomla want to be bombarded with extra information that has nothing to do with their choice of using the software.  Do we have data from users that demonstrates that they want all of this extra community information in their sites?  If we do decide to start pushing extra stuff into user sites, who decides what content is or is not appropriate for that?

**Comment by tonypartridge** [comment] 2017-07-30 15:22
I don't think it's that complicated. You just show Usergroups going on to their location should they click the events section, news of the Joomla! Project and releases. Just basic but useful stuff.

All which can be disabled, so not pushing but informing should they click to view more. We could have a CPanel module which can be disabled too.

**Comment by mbabker** [comment] 2017-07-30 15:35
> show Usergroups going on to their location should they click the events section

This means sending information that makes individual users identifiable (not the server) to the `joomla.org` hosting architecture because we're going to want to show events geographically relevant to them, not where the site is hosted.

> news of the Joomla! Project and releases

Release news is already available.  Is news regarding leadership structure or thank you posts relevant to users who are only using the software and not participating in the community?

> informing should they click to view more

Why should they?  If they're only interested in using the software, why should they be bothered with community happenings or news that has nothing to do with the software, which is what a vast majority of the content outside of our release news posts are?

I personally don't think we just throw some `mod_feed` modules in the default SQL and leave it to users to turn off if they don't want it.  Personally, I would like to see data backing up the desire to make the control panel a marketing arm, if there is a desire from our userbase (not just the few hundred who are active in various project channels that influence most decisions and actions) to have this data then we can work to support this.  But I really don't feel like we should be investing the time and effort into this if it really is all boiling down to a few people having the opinion that the administrator dashboard should be a project marketing arm and the vast majority of the userbase doesn't want to have this kind of content pushed onto them.  For my company clients who are using Joomla, none of them really care I have the position I do within the project let alone want to see info about local events, leadership elections, etc. etc.; they just want the software to work.

**Comment by MATsxm** [comment] 2017-07-30 15:38
> they just want the software to work.

stop making sense 😝

**Comment by netamity** [comment] 2017-07-30 17:54
> it really is all boiling down to a few people having the opinion that the administrator dashboard should be a project marketing arm and the vast majority of the userbase doesn't want to have this kind of content pushed onto them
We don't know that's the case, do we? If you do have the data, then I'd love to see it.
The idea that this would be intrusive or an inconvenience to anyone is completely laughable, and the potential gains for news and community awareness are pretty clear.

**Comment by mbabker** [comment] 2017-07-30 18:02
> The idea that this would be intrusive or an inconvenience to anyone is completely laughable, and the potential gains for news and community awareness are pretty clear.

It is intrusive if you don't have an interest in participating in the software community and are only concerned with use of the software, and that's the one point I want to reiterate until the end of time; not everyone who is using Joomla cares to go to social events, cares who is making the decisions for the project, or that we are working with a Google program that supports college students getting real world experience working with software projects.  And since we lack data showing there is either user interest in having this data in their backends or they'd rather not be bothered, it's going to come down to a few dozen folks who pay attention to various GitHub channels making that decision, and they are going to lean toward a very heavy bias of adding it.

That's why this has to be weighed carefully.  This can't just be a "well we want to get more visibility on stuff, throw it in the backend" decision.  Every aspect from the social to the technical perspective is going to have to be weighed and supported (because adding more RSS or API consumers to our `joomla.org` network is going to cause an increase in resource use if we want to support modules similar to the WordPress widgets, and it will affect the end user who has a less-than-optimal internet connection when they now have to also wait for this external data to be loaded).

**Comment by Joomv** [comment] 2017-07-30 18:10
Also remember almost 50% of Wordpress sites are hosted on wordpress.com - it makes sense in that environment to advertise stuff.  Our install base is different.  

This goes to substantiate what Michael is saying also, this isn't a simple undertaking and has knock on effects.

**Comment by Sandra97** [comment] 2017-07-30 19:13
Why are we always talking about WordPress? We don't have the same target.
We lost most big companies because they switched to Drupal, not to WordPress. We should better look at Drupal and see where they succeeded because it's probably where we failed.

**Comment by Joomv** [comment] 2017-07-30 20:22
Actually we should look at everyone and what they are doing.  Wordpress does a lot right and still shares a space with us, Drupal has shut itself off into the world of the institution.  We also should look at Typo3, Concrete5, Grav, October, Wix, Weebly, all of them.  Look at what they are doing and then ask.

Is this relevant to our global user base?
Would this benefit global user base?
Do we have the man/server/bandwidth power to achieve it
Etc.

In the case of this endeavour,  I honestly believe it made the cut in WP because 50% of their stuff is hosted by them, so its no extra strain and they have the globe liberally covered with stuff that makes their widget worthwhile.  With 50% of their stuff hosted by them, they already know their user's location so its easier less calls, less data requests, different model.

**Comment by ufuk-avcu** [comment] 2017-07-31 08:41
In my opinion, we should don't talk about things we don't know. Like what the user awaits from the Joomla Backend and so on. Everytime we use our gut instincts, it's not helpful for a discussion. It's better to do some little research first. The research does not have to be scientific... For example we have a big Facebook Group https://www.facebook.com/groups/joomlanospam/with 24000+ People in there. Ask them for their opinions about that case. Start a poll or something and then we can see, whether it is a problem or not. Maybe someone find a scientific article about this and so on. Otherwise i see always the same sheme: We argue against each other and not for joomla and we can close this issue after some rounds of discussions, without a clear statement...

**Comment by parthlawate** [comment] 2017-07-31 08:59
I agree with @ufuk-avcu Getting an idea to see if the users will be ok with it is a good idea.. A similar discussion had taken place around gathering stats.. As long as its optional it should be ok.. 

On the point of the user's internet connectivity etc affecting backend loading, we can always have a async ajax request that times out or Caches content to ensure the backend loading is not compromised. What do you think @mbabker  ?

The idea is to see if we can leverage the only tool we have that can really give us reach for any kind of user messaging which is unparalleled to any other medium we have..

**Comment by Joomv** [comment] 2017-08-03 10:24
Here's something else to consider ....  we have 165 listed user groups.  At least 30% of those are very inactive if at all (we've just started another review)  there's probably another 50 out there that are not registered so lets say we have 175 (being positive).  Hardly any of them list their JUG meetings (3-4 at best) so we have no listing for them.

In contrast, Wordpress has 1239 meetups on meetup alone (https://www.meetup.com/topics/wordpress/) - Wordpress pay a lot to be on meetup 

We have around 30 JoomlaDays a year and 2 major events.  At a rough count Wordpress has 117 Wordcamps this year (https://central.wordcamp.org/schedule/)

Given the scale - yes this works well for Wordcamp.  

For us,  when you look at the numbers, not so much

**Comment by ufuk-avcu** [comment] 2017-09-13 07:59
If someone has new arguments for or against this idea, we can open this issue again.

**Closed by ufuk-avcu** 2017-09-13 07:59 UTC
